### ISSUE TITLE
Format of trajectory

### ISSUE THREAD

**Issue by J-You** [MaginnGroup/PyLAT#11]
Thanks for your  selflessly publish this code.

I have got a problem:
"""
beginning COM calculation
Traceback (most recent call last):
  File "PyLAT.py", line 254, in <module>
    (comx, comy, comz, Lx, Ly, Lz, Lx2, Ly2, Lz2) = c.calcCOM(trjfilename,datfilename, ver)
  File "/home/why/PyLAT-master/src/calcCOM.py", line 47, in calcCOM
    (xcol, ycol, zcol, molcol, typecol) = self.getcolumns(trjfilename[0])
  File "/home/why/PyLAT-master/src/calcCOM.py", line 122, in getcolumns
    molcol = inline.index('mol')
ValueError: 'mol' is not in list
"""

It is caused by the different format of my dump file, which is "ITEM: ATOMS id type x y z vx vy vz "
I'm not sure the dump format identified by PYLAT. It seems not exist in "example" distribution.
I also have a problem of what is the difference between 'mol' and 'type', in calcCOM.py, line 122, 123.
In fact, my system don't have molecules. It is all consisted by atoms. 
In my view, both of 'mol' and 'type' signify atom type in data file.

Thanks for your time and attention.

**Comment by mike5603** [comment]
Unfortunately, as of right now PyLAT assumes you have molecules in the system. The purpose of mol is to inform the code which atoms belong to the same molecule. For your system, it is mol and id which would be the same. Type gives information on what element your atom is, not which molecule it is a part of. 

As of right now there is no plan to incorporate atomistic calculations  into the code due to lack of funding and people working on the code. I did write a quick hotfix for another person if you look into the closed issues section of this page titled focus on molecular systems. If you apply that fix you should be able to calculate the properties for atomistic systems

**Comment by J-You** [comment]
Thanks for your reply. I will try to fix the code for my simulation.
